Fix compile process by linking with -lrt
According to the man page 'man clock_gettime', we need to link
with -lrt for glibc versions before 2.17.

This fixes the following error (and similar ones) during the
compilation process:
getmonotonictime.c:(.text+0x15): undefined reference to `clock_gettime'

Signed-off-by: Michael Heimpold <michael.heimpold@i2se.com>